export SHELL:=/bin/bash
export MAKEFLAGS+=--no-print-directory
export DEBUG:=false
export VENDOR:=codemityio
export GOPRIVATE:=github.com/${VENDOR}
export GOTOOLCHAIN:=go$(shell sed -n 's/^go \(.*\)$$/\1/p' go.mod | head -1)
export BASE_NAME:=$(shell basename ${PWD})
export MINIMUM_COVERAGE:=82
