export SHELL:=/bin/bash
export MAKEFLAGS+=--no-print-directory
export DEBUG:=false
export VENDOR:=codemityio
export GOPRIVATE:=github.com/${VENDOR}
export BASE_NAME:=$(shell basename ${PWD})
export MINIMUM_COVERAGE:=82
