@startuml
top to bottom direction
skinparam package {
    BackgroundColor #fafafa
}
skinparam defaulttextalignment center
skinparam noteTextAlignment left
package "github.com/codemityio/go/pkg/env" as github_com_codemityio_go_pkg_env {
    class "<b><font color=#1c1c1c>ErrPkg</font></b>" as github_com_codemityio_go_pkg_env_ErrPkg << (V, #edb4ab) >> {}
    class "<b><font color=#1c1c1c>ErrEnv</font></b>" as github_com_codemityio_go_pkg_env_ErrEnv << (V, #edb4ab) >> {}
    class "<b><font color=#1c1c1c>MustBuild</font></b><font color=#1f38b5>() (*T)</font><[T any]>" as github_com_codemityio_go_pkg_env_MustBuild << (F, #dbcb8f) >> {}
    class "<b><font color=#1c1c1c>MustBuildEnv</font></b><font color=#1f38b5>() (*T)</font><[T any]>" as github_com_codemityio_go_pkg_env_MustBuildEnv << (F, #dbcb8f) >> {}
    class "<b><font color=#1c1c1c>New</font></b><font color=#1f38b5>() (*T, error)</font><[T any]>" as github_com_codemityio_go_pkg_env_New << (F, #dbcb8f) >> {}
    class "<b><font color=#1c1c1c>NewEnv</font></b><font color=#1f38b5>() (*T, error)</font><[T any]>" as github_com_codemityio_go_pkg_env_NewEnv << (F, #dbcb8f) >> {}
}
package "github.com/codemityio/go/pkg/env" as github_com_codemityio_go_pkg_env {
    class "error" as error << (I, #e4f58e) >> {}
    class "error" as error << (I, #e4f58e) >> {}
    class "T" as github_com_codemityio_go_pkg_env_T << (T, #6d8cbf) >> {}
    class "T" as github_com_codemityio_go_pkg_env_T << (T, #6d8cbf) >> {}
    class "T" as github_com_codemityio_go_pkg_env_T << (T, #6d8cbf) >> {}
    class "error" as _error << (I, #e4f58e) >> {}
    class "T" as github_com_codemityio_go_pkg_env_T << (T, #6d8cbf) >> {}
    class "error" as _error << (I, #e4f58e) >> {}
}
package "github.com/codemityio/go/pkg/env" as github_com_codemityio_go_pkg_env {
    github_com_codemityio_go_pkg_env_ErrPkg ...up...|> error
    github_com_codemityio_go_pkg_env_ErrEnv ...up...|> error
    github_com_codemityio_go_pkg_env_MustBuild ....up....> github_com_codemityio_go_pkg_env_T
    github_com_codemityio_go_pkg_env_MustBuildEnv ....up....> github_com_codemityio_go_pkg_env_T
    github_com_codemityio_go_pkg_env_New ....up....> github_com_codemityio_go_pkg_env_T
    github_com_codemityio_go_pkg_env_New ....up....> _error
    github_com_codemityio_go_pkg_env_NewEnv ....up....> github_com_codemityio_go_pkg_env_T
    github_com_codemityio_go_pkg_env_NewEnv ....up....> _error
}
@enduml

